#ifndef _VERSION_H
#define _VERSION_H

// These variables are autogenerated and compiled
// into the library by the version.cmake script
extern "C"
{
    extern const char* GIT_TAG;
    extern const char* GIT_REV;
    extern const char* GIT_BRANCH;
    extern const char* BUILD_TIME;
}

#include <string>
#include <string.h>
#include <stdio.h>
#include "Helper.h"
#include "../../include/webui_storage.h"
#include <algorithm>

std::string getWebUiFileLine(const std::string &path, int lineIndex)
{
    char buf[100] = "?\0";
    FILE *pFile = fopen(path.c_str(), "r");
    if (pFile == NULL) {
        return std::string(buf);
    }

    for (int i = 0; i <= lineIndex; ++i) {
        if (fgets(buf, sizeof(buf), pFile) == NULL) {
            fclose(pFile);
            return std::string("?");
        }
    }
    fclose(pFile);

    std::string value = std::string(buf);
    value.erase(std::remove(value.begin(), value.end(), '\n'), value.end());
    value.erase(std::remove(value.begin(), value.end(), '\r'), value.end());
    return value;
}


const char* build_time(void)
{
    return BUILD_TIME;
}

const char* libfive_git_version(void)
{
    return GIT_TAG;
}

const char* libfive_git_revision(void)
{
    return GIT_REV;
}

const char* libfive_git_branch(void)
{
    return GIT_BRANCH;
}


std::string getFwVersion(void) {
    std::string buf;
    if (std::string(GIT_TAG) == "") { // Tag not set, show branch
        buf = "Development-Branch: " + std::string(GIT_BRANCH);
    }
    else { // Tag is set, ignore branch
        buf = "Release: " + std::string(GIT_TAG);
    }
    buf = buf + " (Commit: " + std::string(GIT_REV) + ")";

    return buf;
}

std::string getHTMLversion(void){
    return getWebUiFileLine(FormatFileName(getWebUiFilePath("/version.txt")), 0);
}

std::string getHTMLcommit(void){
    return getWebUiFileLine(FormatFileName(getWebUiFilePath("/version.txt")), 1);
}

#endif // _VERSION_H
